name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  gradle:
    name: "Build and publish plugin"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - shell: bash
        env:
          GRADLE_PLUGIN_PUBLISH_KEY: ${{ secrets.GRADLE_PLUGIN_PUBLISH_KEY }}
          GRADLE_PLUGIN_PUBLISH_SECRET: ${{ secrets.GRADLE_PLUGIN_PUBLISH_SECRET }}
        run: |
          ./gradlew publishPlugins -i -Pgradle.publish.key="${GRADLE_PLUGIN_PUBLISH_KEY}" -Pgradle.publish.secret="${GRADLE_PLUGIN_PUBLISH_SECRET}"
